### ISSUE TITLE
:loudspeaker: Kairos release v2.3.0

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#1066]
## 🗺 What's left for release

:art:  UX  ( #773 )
- [x] https://github.com/kairos-io/kairos/issues/209

:book: Media/Blog posts ( #774 )
:robot: CAPI ( https://github.com/kairos-io/kairos/issues/120 )

:lock: CoCo/Security (https://github.com/kairos-io/kairos/issues/347)
- [x] https://github.com/kairos-io/kairos/issues/1113
- [x] https://github.com/kairos-io/kairos/issues/1150
- [x] #362 
- [X] #1539 
- [x] https://github.com/kairos-io/kairos/issues/361
- [ ] https://github.com/kairos-io/kairos/issues/1201

ARM:
- [x] https://github.com/kairos-io/kairos/issues/1435

:seedling: Generic
- [ ] #1221 

:bug: Bugfixing

- [x] https://github.com/kairos-io/kairos/issues/1486
- [x] https://github.com/kairos-io/kairos/issues/1448

:gear: Maintenance

- [x] https://github.com/kairos-io/kairos/issues/1430

## ✅ Release Checklist

- [x] **Stage 0 - Finishing Touches**
    - [x] Check kairos/packages, and for any needed update
    - [x] Make sure CI tests are passing.
    - [x] Consider cutting an `rc`, `alpha`, ... based on changes on the CI
- [x] **Stage 1 - Manual testing**
  - How: Using the assets from master, make sure that test scenarios not covered by automatic tests are passing, and that docs are still aligned
    - [x] Fedora flavor install, and manual upgrade works
    - [x] ARM images (openSUSE, alpine) boots and manual upgrade works
- [x] **Stage 3 - Release**
  - [x] Tag the release on master.
- [x] **Stage 4 - Update provider-kairos**
  - [x] Update go mod to consume `kairos-io/kairos`.
  - [x] Check if any changes on the pipelines and building pieces are required
    - [x] Flavor changes
    - [x] `osbuilder` version bumps
  - [x] Update the `CORE_VERSION` file of `kairos-io/provider` to match the release tag of `kairos-io/kairos`
  - [x] Tag the release on `provider-kairos`
- [x] **Stage 5 - Announcement**
  - https://github.com/kairos-io/kairos-docs/pull/52

**Comment by mauromorales** [comment]
## Stage 1 QA results:

- Installed and manual upgrade works, however the newly installed os-release had contents for opensuse-leap and it was only after install that I saw the proper fedora ones
- ARM
  - openSUSE leap boots properly, manual upgrade errors with the following mesage: `failed reading installation state: open /run/initramfs/cos-state/state.yaml: no such file or directory`. Agent version 2.1.9
  - alpine (pending)

cc @mudler @Itxaka

**Comment by Itxaka** [comment]
> ## Stage 1 QA results:

>     * ARM
>       
>       * openSUSE leap boots properly, manual upgrade errors with the following mesage: `failed reading installation state: open /run/initramfs/cos-state/state.yaml: no such file or directory`. Agent version 2.1.9


That its just a warning and its expected on arm. On install that file is created but of course, on arm there is no install so it cannot read that file. Still its an optional file for now..

**Comment by mauromorales** [comment]
@Itxaka ok makes sense, that it would be a warning, however it panics for me. Or is the "manual upgrade" supposed to be done in a different way on ARM?

**Comment by Itxaka** [comment]
> @Itxaka ok makes sense, that it would be a warning, however it panics for me. Or is the "manual upgrade" supposed to be done in a different way on ARM?

In that case the issue is a different one, it should not have anything to do with the state.yaml 👍

**Comment by mauromorales** [comment]
Similar thing in Alpine

![image](https://github.com/kairos-io/kairos/assets/433958/5fde3909-eb94-41bc-a89a-ba21a058bb62)

**Comment by mauromorales** [comment]
Opened https://github.com/kairos-io/kairos/issues/1593 because of the previously mentioned issue. Adding the blocked label

**Comment by mauromorales** [comment]
fixed now on master with the latest agent bump 667e67167801d52eb1e145401d6634195f6b1a84 doing new QA
