### ISSUE TITLE
:building_construction: Kairos factory - Streamline derivatives creation

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#116]
This card is the epic to track all the issues related to streamlining derivatives creation. This includes all the tools, design document, flows in place in order to get full OS image building easied out and also carried in Kubernetes native contexts, including onboarding.

The ultimate goal is to be able to convert upstream images directly with our CRD and artifacts built from our factory - if someone wants can build them manually or just use ours.

## Design goals
- Be able to create a derivative from a Dockerfile with standard container build tools (buildah, docker, etc.)
- Be able to create a derivative from a Kubernetes manifest CRD, using also artifacts from the Kairos factory in a "static", immutable way. Instead of running dynamic commands, we focus on statically creating high reproducible builds of images.
- Be able to create custom OS from Kairos core releases from the CRD and a dedicated CLI with additional customizations: such as kernel, packages, etc.
- Be able to create assets to boot the OS in different scenarios: raw disk images for cloud, ISOs for baremetal, disk images for embedded platforms, netboot artifacts for booting from network
- Be able to netboot seamlessly from network with zero-touch infrastructure configuration - plugging into the existing network with our CRDs.
- Be able to create your own Kairos factory artifacts
- Be able to SBOM, sign, and trace all the artifacts in #92 and #51 

--- 

MVP:
- [x] #270
- [x] #272
- [x] #297
- [x] #300
- [x] CRD to generate custom OS images. input: cloud-init, set of bundles, a base image https://github.com/c3os-io/osbuilder
- [x] #299
- [x] #377 
- [x] #296
- [x] #273
- [x] #515
- [x] https://github.com/kairos-io/kairos/issues/777
- [x] #298
- [x] #514
- [x] #755
- [x] #1044 
- [x] https://github.com/kairos-io/kairos/issues/776
- [x] https://github.com/kairos-io/osbuilder/pull/22
- [x] https://github.com/kairos-io/osbuilder/pull/23
- [x] https://github.com/kairos-io/kairos/issues/711
- [x] #513
- [x] https://github.com/kairos-io/kairos/issues/932
- [x] https://github.com/kairos-io/kairos/issues/1042

Deliverables:
- [x] https://github.com/kairos-io/kairos/issues/430
- [x] https://github.com/kairos-io/kairos/issues/712
- [x] #269
- [x] #301
- [ ] redesign osbuilder CRDs for v1
- [x] Create provider packages in our luet repositories, that can be consumed as a bundles during installation
- [x] Create provider live layer packages for systemd-sysext
- [x] https://github.com/kairos-io/kairos/issues/258
- [x] #384 
- [x] osbuilder: Push artifacts to PVC https://github.com/kairos-io/osbuilder/pull/22/files#diff-7263fc341f1b59afdc8599e1f570cdd180c28bf8cca71ecee1e58b58131202c5R44
- [x] osbuilder: Push artifact to minio
- [x] https://github.com/kairos-io/kairos/issues/451
- [x] #1055 
- [x] #432 
- [x] https://github.com/kairos-io/kairos/issues/1726
- [ ] #1913
- [ ] https://github.com/kairos-io/kairos/issues/455
- [ ] https://github.com/kairos-io/kairos/issues/435
- [ ] https://github.com/kairos-io/kairos/issues/958
- [ ] https://github.com/kairos-io/kairos/issues/511
- [ ] https://github.com/kairos-io/kairos/issues/1896
- [ ] https://github.com/kairos-io/kairos/issues/1898

After MVP phase is concluded, we should have all the cards to track deliverables opened, and we can close this epic.

**Comment by mudler** [comment]
closing this in favor of the follow-up (https://github.com/kairos-io/kairos/issues/1914) . We now are far away from a MVP ( see https://kairos.io/docs/reference/build-from-scratch/ )
