### ISSUE TITLE
SLSA compliance

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#215]
This is an Epic to track the various tickets to enable upgrades with images verified with `cosign` and to have a SLSA compliant chain.

- [x] https://github.com/kairos-io/kairos/issues/431
- [x] #564 
- [x] #51 
- [ ] https://github.com/kairos-io/kairos/issues/92
- [ ] build Image checksum (mtree bootcheck, mtree hash generation)
- [ ] Implement checksums of dependencies in Hadron builds (work left [from here](https://github.com/kairos-io/kairos/issues/3705))

**Comment by ci-robbot** [comment]
Triage: this epic is further along than the checklist shows. Four of six items are done, one is obsolete, and the whole thing now reduces to a single blocked item. Checked against `master` and `kairos-io/hadron@main`.

| Item | State | Evidence |
|---|---|---|
| #431 SLSA | done, already ticked | closed |
| #564 kyverno gate | done, already ticked | closed |
| #51 SBOM | done, already ticked | closed |
| Checksums of dependencies in Hadron builds (from #3705) | **done, needs ticking** | see below |
| build Image checksum (mtree bootcheck, mtree hash generation) | **obsolete** | see below |
| #92 SLSA level 3 base images | open, **blocked** | see below |

## Hadron dependency checksums: done

#3705 closed on 2026-02-16, and the result is in place. `kairos-io/hadron@main` has `sources.yaml` as the single source of truth, with a pinned `sha256` for every one of its ~106 packages, and `.github/workflows/populate-sources.yml` enforces it rather than recording it:

```
# populate-sources.yml:259-265
actual=$(sha256sum "$out" | awk '{print $1}')
...
echo "  SHA256 mismatch (expected $EXPECTED_SHA, got $actual), trying next URL"
```

A mismatch fails the cell, so a retagged or substituted upstream tarball cannot enter a build. Automated bumping updates the hash alongside the version, which was the other half of #3705. This item can be checked off.

## mtree image checksum: obsolete

`grep -rni mtree` over `master` returns nothing. mtree bootcheck and mtree hash generation were elemental-era machinery and left with it; integrity of the shipped images is now covered by different mechanisms (dm-verity for sysext/confext under Trusted Boot, cosign signing, UKI measurement). Suggest striking this line rather than leaving it as an open commitment nobody intends to build.

## What is left

Only #92, and it is blocked on #4009 (per @mudler's note there, 2026-03-16), which is itself still open. So this epic is not actionable as a whole until #4009 lands.

Suggested resting state: tick the Hadron checksums item, strike the mtree item, and note in the description that the epic tracks #92 only and is gated on #4009. That makes it honest at a glance instead of looking like a five-item backlog. @mauromorales @jimmykarily, one of you owns the edits since I cannot change the description.
