### ISSUE TITLE
Align documentation to current featureset

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#274]
**Is your feature request related to a problem? Please describe.**
Currently documentation are matching several areas. This ticket purpose is to track all individual cards in order to have a good, consolidated documentation basis.

**Tickets**
- [x] #214 
- [x] https://github.com/kairos-io/kairos/issues/58
- [x] https://github.com/kairos-io/kairos/issues/48
- [x] https://github.com/kairos-io/kairos/issues/8
- [ ] https://github.com/kairos-io/kairos/issues/6
- [ ] docs: OS Onboarding
- [ ] docs: CAPI
- [ ] #618 
- [x] #624 
- [ ] #538 
- [x] #279
- [ ] https://github.com/kairos-io/kairos/issues/70
- [x] https://github.com/kairos-io/kairos/issues/224

**Comment by mudler** [comment]
I think we can close this in favor of the cards left open - docs are now in much of a better shape then back then.
