### ISSUE TITLE
:lock_with_ink_pen: [epic] Trusted Boot

### ISSUE THREAD

**Issue by mudler** [kairos-io/kairos#347]
This is an Epic to track all the progress toward Trusted boot/SENA with Kairos.

:penguin: Booting, Installation, Upgrading

UKI support in Kairos has several implications:
1. The current lifecycle management code needs to be isolated to be "swappable"
2. UKI images will be generated by `osbuilder`
3. UKI inputs are still container images of Kairos, but the images needs to be hybrid and be able to boot also without pivoting, on demand
4. There is a new backend manager which manages upgrades in UKI mode

Measured booting will be supported only in UKI mode 

- [x] https://github.com/kairos-io/kairos/issues/625
- [x] https://github.com/kairos-io/immucore/pull/61
- [x] #657
- [x] #871
- [x] #1150
- [x] #1201
- [x] #1151
- [x] #1152
- [x] #872
- [x] #868
- [x] #1153
- [x] #873
- [x] #656
- [x] #870
- [x] #1115
- [x] #869
- [x] #2166 
- [x] #1154

:lock_with_ink_pen: Encryption:
- [x] https://github.com/kairos-io/kairos/issues/1155
- [x] https://github.com/kairos-io/kairos/issues/1156
- [x] #119 
- [x] #161  

Releases:

- [x] https://github.com/kairos-io/kairos/issues/1792
- [x] #1791

**Comment by mudler** [comment]
Closing as this was part of 3.x
